### ISSUE TITLE
thoughts

### ISSUE THREAD

**Issue by jamestalmage** [jamestalmage/append-transform#1]
@novemberborn

Take a look at this.

It's basically your `nyc` implementation with a few changes.

1. Never uses `Module.prototype`, ~~instead it does~~:

  ```js
// redacted - no longer true
  ```

2. Uses `Object.getPropertyDescriptor`, and if it sees registered `getter` / `setter`, will forward updates to them.

**Comment by jamestalmage** [comment]
So... I think I ended up inadvertently solving https://github.com/bcoe/nyc/issues/70

Initially, this was going to be a listener that AVA used to watch how extensions installed behaved and decide whether or not to disable our test transforms (it still could be used for that).

Check out the test suite, specifically the last 4 tests.

**Comment by jamestalmage** [comment]
// @bcoe

**Comment by jamestalmage** [comment]
So, I am not sure what the heck to call this thing, or what it does.

Check out: [this test](https://github.com/jamestalmage/require-extension-listener/blob/master/test/execution-order.js).

It now realize @novemberborn's clever hook really does, is ensure that `nyc`s `istanbul` transform is applied last, so it can collect all the source-map information from downstream transforms. I didn't fully understand that when I dove into this.

**Comment by jamestalmage** [comment]
(note that in the test "wrapped" transforms are installed with this library, "conventional" would be one installed via something like `pirates`).

**Comment by novemberborn** [comment]
@jamestalmage this is nice! I like how it retains `require.extensions` as the API. Hooking into the lower level implementation makes it easier to retain compatibility with existing code (important for testing frameworks).

How does it deal with a new hook calling a previously stored reference to `require.extensions['.js']`? It probably wouldn't call `_compile()` in that case, meaning `originalCompile` is never restored.

**Comment by jamestalmage** [comment]
After installation, any reference to `require.extensions['.js']` contains a reference to a wrapped hook instance. Any wrapped hook instance is going to replace `._compile` on it's own.

I'm like 60% sure of this :smile:

**Comment by jamestalmage** [comment]
@novemberborn 
see https://github.com/jamestalmage/require-extension-listener/commit/0f6da01e494b411087ca35e73f01216ef6b1659b

Do you think that covers all the scenarios you were thinking of?

**Comment by novemberborn** [comment]
@jamestalmage yea, quite extensively I must say.

I wonder if this should have a "revert" API like `pirates`? Right now if a hook decides to uninstall itself it also uncouples subsequent hooks.

**Comment by jamestalmage** [comment]
Maybe. Created #2

**Comment by jamestalmage** [comment]
Just published [`append-transform@0.2.0`](https://www.npmjs.com/package/append-transform), thanks for helping me think this through.
