### ISSUE TITLE
Needs a better name.

### ISSUE THREAD

**Issue by jamestalmage** [jamestalmage/append-transform#4]
To me `capture-require` doesn't really describe what this thing does.

Installing hooks the conventional way (i.e. using `pirates`):

```js
pirates(fooTransform);
pirates(barTransform);
```

The transforms are applied **in order** (`fooTransform`, then `barTransform`).

This module guarantees your transform will be applied last, even as other conventional modules continue to be installed afterwords:

```js
captureRequire(transformA); // guaranteed last
captureRequire(transformB); // guaranteed second to last
pirates(transformC);
pirates(transformD);
```

These transforms would be applied in the following order:

`c` -> `d` -> `b` > `a`

The initial use case is for `nyc` to ensure it is able to capture the source map at the very end of the transform chain.

I am having trouble coming up with a name that describes it at all. I feel `capture-require` is a bit misleading (I would expect a module with that name to behave more like `pirates`) 

// @novemberborn @bcoe @sindresorhus @ariporad @vdemedes

**Comment by novemberborn** [comment]
`bookend`?

**Comment by sindresorhus** [comment]
`append-transform`

**Comment by jamestalmage** [comment]
I went with [`append-transform`](https://www.npmjs.com/package/append-transform).
