### ISSUE TITLE
Is this supposed to work?

### ISSUE THREAD

**Issue by gotwarlost** [jamestalmage/append-transform#5]
Trying to use `append-transform` in the istanbul hook for the always-last execution feature.

One of my tests failed. Repro case below.

```
$ cat x.js
var a = require('append-transform'),
    t = function (code, file) { return code; };

a(t, '.es6');
$ node x.js 
/tmp/istanbuljs/istanbul-lib-hook/node_modules/append-transform/index.js:19
		((descriptor.get || descriptor.set) && !(descriptor.get && descriptor.set)) ||
		            ^
TypeError: Cannot read property 'get' of undefined
    at appendTransform (/tmp/istanbuljs/istanbul-lib-hook/node_modules/append-transform/index.js:19:15)
    at Object.<anonymous> (/tmp/istanbuljs/istanbul-lib-hook/x.js:4:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

```

**Comment by jamestalmage** [comment]
Yep it should. I see what's wrong. My code assume's you are adding one for an extension that has an existing extension. It does not take into account the ability to add new extensions (`.es6` in this case).

Give me a few minutes and I'll publish a fix.

**Comment by jamestalmage** [comment]
@gotwarlost [New tests covering this behavior](https://github.com/jamestalmage/append-transform/blob/6b6e73b18c40a47e8639f31d80ab18cc1c5379a9/test/test.js#L96-L124)

Make sense to you?

**Comment by gotwarlost** [comment]
Excellent. Thanks a bunch!

**Comment by gotwarlost** [comment]
Could you rev this in npm?

**Comment by jamestalmage** [comment]
`0.3.0` released!

**Comment by gotwarlost** [comment]
Thanks!

**Comment by jamestalmage** [comment]
Just an FYI - it appears my fix isn't a perfect emulation of what Node does by default. See #6.
