### ISSUE TITLE
Better emulate standard `require` for extensions that are not specified:

### ISSUE THREAD

**Issue by jamestalmage** [jamestalmage/append-transform#6]
Right now, if you do:

```js
appendTransform(transformFn, '.foo');
```

And no one ever registers a handler for `.foo`, we throw an error.

Without `append-tranform` what [actually happens](https://github.com/nodejs/node/blob/19f700859b55b96c7ed9bdeb68482c6a9d84e1b2/lib/module.js#L365-L367) is that Node just tries to load it as a `.js` file.

This should be fixed.

Related: #5 

// @gotwarlost

**Comment by jamestalmage** [comment]
As I see it there are two options for when `require.extensions['.foo'] === undefined`.

1. We pass through to the `.js` extension:

  ```js
  function defaultHook(module, filename) {
    return require.extensions[`.js`](module, filename);
  }
  ```
  
  This would run through the list of extensions for `.js`, followed by whatever future hooks were installed for `.foo`. 

  Pro:
  - It provides a slightly closer experience to the default require setup if no handler is ever installed. 
  - You can just add your append-transform to `.js` and let Node automatically apply it for `.es6`, etc.

  Con:
  - It could create weird scenarios where you try to install coverage twice (istanbul installations for `.js` and `.es6` both get executed), etc.

2. We implement the standard default behavior ourself:

  ```js
  function defaultHook(module, filename) {
    var content = fs.readFileSync(filename, 'utf8');
    module._compile(stripBom(content), filename);
  }
  ```

  Con:
  - You must now install for every extension explicitly (i.e. `.es6` in addition to `.js`, etc). 
  - This has implications for extensions outside your control. For example, if Babel were to only install for `.js` and expect `.es6` files to follow along - this would break that.

  Pro:
  - I think it's more straightforward, easier to follow what's happening.

I'm leaning towards `2`. My only concern is the Babel example I listed as a con for `2`, but I think that would be a bad choice on Babel's part anyways (I'm not actually picking on Babel here - I don't know how they do it - this is all hypothetical).

**Comment by novemberborn** [comment]
:+1: on `2`. This stuff is hard enough as it is, keeping it explicit seems preferable.

**Comment by jamestalmage** [comment]
I went with `2`, deployed as `0.4.0`

cc: @gotwarlost
